kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-mongodb-standalone
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
#volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
