server:
  ha:
    raft:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        seal "azurekeyvault" {
          client_id      = "${client_id}"
          client_secret  = "${client_secret}"
          tenant_id      = "${tenant_id}"
          vault_name     = "${vault_name}"
          key_name       = "${key_name}"
        }
        service_registration "kubernetes" {}